name: Create and publish a Docker image
on: 
    workflow_dispatch:
    workflow_call:
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: nigeldixon/kobo-book-downloader
    REPO: ${{ github.repository_owner }}/kobo-book-downloader
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                repository: ${{ env.REPO }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    
            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:nightly
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
                provenance: false
